### ISSUE TITLE
symbols should be allowed as hash keys

### ISSUE THREAD

**Issue by gamemachine** [mattyoho/tnetstring-rb#5]
symbols for hash keys are common in ruby, and someone who has an existing large hash structure is not going to stringify the keys recursively before encoding.

**Comment by gamemachine** [comment]
Just to add to this.  Most ruby serializers just call to_s on the content also, so if you are storing dates and such it just works.
This is defnitely the right thing to do in 1.8 as strings are just raw bytes.  Not sure how that might effect binary data in 1.9?

**Comment by mattyoho** [comment]
I think you're correct and will make the change soon.

**Comment by gamemachine** [comment]
Hey btw I was doing some performance testing a couple days ago and ran
into a decoding issue with larger payloads.  It gets exponentially
more expensive to decode.  I took a real world data structure (23mb
yaml file) and decoding was around 3 seconds, but encoding was 3-4
minutes.  I also gained a measurable performance gain by changing
encode so it takes everything that gets converted into the right form
automatically when you call to_s on it, like true/false and symbols,
and not calling responds_to on those, and not explicitly calling to_s,
as the interpolation does that automatically.  basically put the hash,
array, and null at the top and just turn everything else into a
string.

Also, in parse_pair the value can be null.

Chris

On Fri, Jun 17, 2011 at 4:10 PM, mattyoho
reply@reply.github.com
wrote:

**Comment by mattyoho** [comment]
Symbols are now allowed as hash keys, and corrected to restriction on null hash values.

I'm not going to address too much on the optimization front, as the routines will be rewritten as native implementations soon.

As for the performance over large data structures, I believe that a misapplied use case, really. The idea of tnetstrings is for sending small, regular packets of data over a network connection. Things such as state packets for a networked game or something of the like. It's a near real-time transmission format, and as such a 23MB file falls outside the range of pathological. While I'm not opposed to performance improvements, that particular use case doesn't isn't in current scope of the library.

Thanks for your feedback. If you feel further discussion is warranted, feel free to open another issue.
